### PR TITLE
Somewhat more idiomatic SSReflect

### PR DESCRIPTION
**Pull request by clayrat**
It's usually a good idea to terminate every branch with `by` so that in case of breaking changes the proofs don't spill over.

### CODE REVIEW

**Comment by jonsterling** [comment]
@clayrat Thanks! But I thought that Coq's bullets prevent the spillage; am I mistaken?

**Comment by clayrat** [comment]
I try not to rely on bullets, as sometimes their behavior switches for me to cosmetic even without explicit `Set Bullet Behavior "None"`.

Btw, `ClosedModality.v` doesn't seem to work for me: 

```
File "./theories/ClosedModality.v", line 28, characters 30-41:
Error: Illegal application (Non-functional construction): 
The expression "Rel" of type "Type"
cannot be applied to the term
 "T A ϕ" : "Dcpo.type"
```

**Comment by jonsterling** [comment]
I find that the bullets are reliable in my environment; I prefer not to use `by` when the bullet is doing it for the following (very silly) reason: Emacs is basically incapable of indenting code that involves `by` correctly, meaning that it is extremely frustrating for me to edit that code... :(

**Comment by jonsterling** [comment]
P.S. That file builds for me. Can you tell me what version of Coq you are using?

**Comment by clayrat** [comment]
```
The Coq Proof Assistant, version 8.13.2 (April 2021)
compiled on Apr 28 2021 11:55:36 with OCaml 4.11.1
```

Also, I'm using `coq-hierarchy-builder 1.1.0` and `oq-mathcomp-ssreflect 1.12.0`.

**Comment by jonsterling** [comment]
Huh; not sure it makes a difference, but what I have is:

```
The Coq Proof Assistant, version 8.13.2 (June 2021)
compiled on Jun 15 2021 23:45:36 with OCaml 4.12.0
```

I have the same versions of HB and ssreflect as you too. So I am not sure what to tell you...

**Comment by clayrat** [comment]
Ah, never mind, I've missed that `D` in OrderSpace is not implicit anymore. 

So, shall I revert the changes moving `by` to the start of the line? Does it work for you if the `by` is hidden after a semicolon?

**Comment by jonsterling** [comment]
Let's keep your changes and see how they work :) Thank you!

P.S. I'm sorry for all the crazy merge conflicts I'm causing.  I am stupidly committing the html to the repo in order to get github  pages published, but obviously this isn't the best way to do it.

**Comment by jonsterling** [comment]
(I won't commit anymore until after this is merged, I promise! 😆 )

**Comment by clayrat** [comment]
Thanks for merging! Btw, I've previously added `is_monotone` to `Poset.v` because I was working on Kleene's FP theorem, so you might want to drop either it, or the new def in `Dcpo.v`.

**Comment by jonsterling** [comment]
oh sick!

**Pull request merged**
